token: 
ptero:
  url: https://panel.nightservers.xyz
  api_key: 

api:
  server:
    info_url: https://api.nightservers.xyz/server/info.php?id=
admin:
  - 184720162472198144
  - 422773039084601344
  - 734765089273675837
  - 253937964193677323


embed:
  onayrenk: 0x5efafa
  hatarenk: 0xe85b45
  market:
    huba: 0x51ff53
